create table countries (
    id bigint generated by default as identity primary key,
    name varchar(255) not null ,
    continent varchar(255) not null
);

create table authors (
    id bigint generated by default as identity primary key,
    name varchar(255) not null ,
    surname varchar(255) not null ,
    country_id bigint not null,

    foreign key (country_id) references countries(id)
);

create table library_users (
    username varchar(255) primary key,
    password varchar(255),
    name varchar(255),
    surname varchar(255),
    is_account_non_expired boolean default true,
    is_account_non_locked boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled boolean default true,
    role varchar(50)
);

create table books (
    id bigint generated by default as identity primary key,
    name varchar(255) not null ,
    category varchar(255) not null,
    author_id bigint not null,

    foreign key (author_id) references authors(id)
);

create table book_inventory (
    id bigint generated by default as identity primary key,
    available_copies int,
    book_id bigint not null,

    foreign key (book_id) references books(id) on delete cascade on update cascade
);

create table user_wishlists (
    user_id varchar(255) not null,
    book_id bigint not null,

    primary key (user_id, book_id),
    foreign key (user_id) references library_users(username),
    foreign key (book_id) references books(id)
);